import Head from 'next/head';
import { useEffect, useState } from 'react';
import Loader from '../components/Loader';
import Content from '../components/Content';

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 2000);
  }, []);

  return (
    <>
      <Head>
        <title>Bryan Bandela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      {loading ? <Loader /> : <Content />}
    </>
  );
}
